<?php
$meituan='{"data":"data","shop":"shop","product":{"id":"deal_id","title":"deal_title","category":"deal_cate","city":"city_name","validFrom":"start_time","validThrough":"end_time","description":"deal_desc","name":"deal_url","purchase_count":"sales_num"},"discount":{"original_price":"value","present_price":"price"},"location":{"address":"shop_addr","latitude":"shop_lat","longitude":"shop_long"},"img":{"name":"deal_img"},"cate":{"餐饮":"餐饮美食","健康丽人":"健康美容","零售":"商品零售","生活服务":"生活服务","文体娱乐":"休闲娱乐"},"website":"美团"}';

$lashou='{"data":"url","shop":"shop","product":{"id":"gid","title":"title","category":"cate","city":"city","validFrom":"startTime","validThrough":"endTime","description":"detail","name":"loc","purchase_count":"bought"},"discount":{"original_price":"value","present_price":"price"},"location":{"address":"addr","latitude":"latitude","longitude":"longitude"},"img":{"name":"image"},"cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"website":"拉手"}';

$wowo='{"data":"deal","shop":"division_name","product":{"id":"id","title":"title","category":"cate","city":"division_name","validFrom":"start_date","validThrough":"end_date","description":"detail","name":"deal_url","purchase_count":"quantity_sold"},"discount":{"original_price":"value","present_price":"price"},"location":{"address":"address","latitude":"lat","longitude":"lng"},"img":{"name":"medium_image_url"},"cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"website":"窝窝团"}';

$nuomi='{"data":"url","shop":"shop","product":{"id":"loc","title":"title","category":"category","city":"city","validFrom":"startTime","validThrough":"endTime","description":"detail","name":"loc","purchase_count":"bought"},"discount":{"original_price":"value","present_price":"price"},"location":{"address":"addr","latitude":"latitude","longitude":"longitude"},"img":{"name":"image"},"cate":{"1":"餐饮美食","3":"健康美容","4":"商品零售","2":"休闲娱乐"},"website":"糯米"}';

$ftuan='{"data":"url","shop":"shop","product":{"id":"loc","title":"title","category":"cate","city":"city","validFrom":"startTime","validThrough":"endTime","description":"detail","name":"loc","purchase_count":"bought"},"discount":{"original_price":"value","present_price":"price"},"location":{"address":"addr","latitude":"latitude","longitude":"longitude"},"img":{"name":"image"},"cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"website":"F团"}';

$manzuo='{"data":"url","shop":"city","product":{"id":"image","title":"title","category":"cate","city":"city","validFrom":"startTime","validThrough":"endTime","description":"description","name":"loc","purchase_count":"bought"},"discount":{"original_price":"value","present_price":"price"},"location":{"address":"addr","latitude":"latitude","longitude":"longitude"},"img":{"name":"image"},"cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"website":"满座"}';

