<?php
$meituan='{"data":"data","shop":"shop","id":"deal_id","title":"deal_title","category":"deal_cate","city":"city_name","validFrom":"start_time","validThrough":"end_time","description":"deal_desc","url":"deal_url","purchase_count":"sales_num","original_price":"value","present_price":"price","shop_name":"shop_name","address":"shop_addr","latitude":"shop_lat","longitude":"shop_long","picture":"deal_img","cate":{"餐饮":"餐饮美食","健康丽人":"健康美容","运动健身":"健康美容","零售":"商品零售","生活服务":"生活服务","摄影":"休闲娱乐","文体娱乐":"休闲娱乐","休闲娱乐":"休闲娱乐","丽人":"健康美容","中餐":"餐饮美食","异国餐饮":"餐饮美食","火锅":"餐饮美食","其它餐饮":"餐饮美食","自助餐":"餐饮美食","酒店旅游":"酒店旅游","活动单":"未知"},"source":"美团"}';

$lashou='{"data":"url","shop":"shop","id":"gid","title":"title","category":"cate","city":"city","validFrom":"startTime","validThrough":"endTime","description":"detail","url":"loc","purchase_count":"bought","original_price":"value","present_price":"price","shop_name":"name","address":"addr","latitude":"latitude","longitude":"longitude","picture":"image","cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"source":"拉手"}';

$wowo='{"data":"deal","shop":"division_name","id":"id","title":"title","category":"cate","city":"division_name","validFrom":"start_date","validThrough":"end_date","description":"detail","url":"deal_url","purchase_count":"quantity_sold","original_price":"value","present_price":"price","shop_name":"shop_name","address":"address","latitude":"lat","longitude":"lng","picture":"medium_image_url","cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"source":"窝窝团"}';

$nuomi='{"data":"url","shop":"shop","id":"loc","title":"title","category":"category","city":"city","validFrom":"startTime","validThrough":"endTime","description":"detail","url":"loc","purchase_count":"bought","original_price":"value","present_price":"price","shop_name":"name","address":"addr","latitude":"latitude","longitude":"longitude","picture":"image","cate":{"1":"餐饮美食","3":"健康美容","4":"商品零售","2":"休闲娱乐"},"source":"糯米"}';

$ftuan='{"data":"url","shop":"shop","id":"loc","title":"title","category":"cate","city":"city","validFrom":"startTime","validThrough":"endTime","description":"detail","url":"loc","purchase_count":"bought","original_price":"value","present_price":"price","shop_name":"shop_name","address":"addr","latitude":"latitude","longitude":"longitude","picture":"image","cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"source":"F团"}';

$manzuo='{"data":"url","shop":"city","id":"loc","title":"title","category":"cate","city":"city","validFrom":"startTime","validThrough":"endTime","description":"description","url":"loc","purchase_count":"bought","original_price":"value","present_price":"price","shop_name":"shop_name","address":"addr","latitude":"latitude","longitude":"longitude","picture":"image","cate":{"美食":"餐饮美食","美容":"健康美容","网购":"商品零售","优惠券":"生活服务","休闲":"休闲娱乐"},"source":"满座"}';
?>
